
import static java.lang.Math.abs;
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : AttackWeakest.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//
public class AttackWeakest extends Strategy {

    @Override
    public void act(Knight knight) {
        Random rand = new Random();
        int chance = rand.nextInt(5);

        if (knight.getTeam() == 0) {
            int minHealth = 1000;
            for (int j = 0; j < Simulation.getInstance().elmoradList.size(); j++) {
                if ( Simulation.getInstance().elmoradList.get(j).getHealth() < minHealth && Simulation.getInstance().elmoradList.get(j).getDead() == 0) {
                    knight.setTarget(Simulation.getInstance().elmoradList.get(j));
                    minHealth = Simulation.getInstance().elmoradList.get(j).getHealth();
                }
            }
        } else if (knight.getTeam() == 1) {
            int minHealth = 1000;
            for (int j = 0; j < Simulation.getInstance().karusList.size(); j++) {
                if ( Simulation.getInstance().karusList.get(j).getHealth() < minHealth && Simulation.getInstance().karusList.get(j).getDead() == 0) {
                    knight.setTarget(Simulation.getInstance().karusList.get(j));
                    minHealth = Simulation.getInstance().karusList.get(j).getHealth();
                }
            }
        }
        boolean touch = false;
        if (knight.getTarget() != null) {
            if (chance == 0 || knight.getSpecialFlag() == 1) {
            	touch = knight.rangedAttack();
             } 
             else if (knight.getSpecialFlag() != 1) {
                touch = knight.meleeAttack();
            }

            if (!touch) {
                if (knight.getxPos() - knight.getTarget().getxPos() < -20) {
                    knight.setxPos(knight.getxPos() + knight.getSpeed() / 25);
                } else if (knight.getxPos() - knight.getTarget().getxPos() > 20) {
                    knight.setxPos(knight.getxPos() - knight.getSpeed() / 25);
                }
                if (knight.getyPos() - knight.getTarget().getyPos() < -20) {
                    knight.setyPos(knight.getyPos() + knight.getSpeed() / 25);
                } else if (knight.getyPos() - knight.getTarget().getyPos() > 20) {
                    knight.setyPos(knight.getyPos() - knight.getSpeed() / 25);
                }

            }

        }
    }
}
