import java.awt.Graphics;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : BasicKnight.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//




public abstract class BasicKnight extends Knight
{
	 public BasicKnight(int id,int xPos, int yPos, int hitPoint,
			int score, int speed, int health, Strategy strategy,int team, int type,  Knight target) {
		super(id,xPos, yPos, hitPoint, score, speed, health, strategy, team,type,target);
		// TODO Auto-generated constructor stub
	}

	 public abstract void draw(Graphics g);
}
