
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Offline
//  @ File Name : MoveRandomly.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//
public class drawDiamond extends Strategy {


    public void act(Knight knight) {
        // TODO Auto-generated method stub

        Pair generatedPos = randomNumberGenerator(knight.getxPos(), knight.getyPos(), knight.getSpeed());
        /*if(knight.getxPos() < 400 || knight.getxPos() > 700)
        {
            generatedPos = whichRegion(knight.getxPos(), knight.getyPos());
        }
        else
        {
            generatedPos = randomNumberGenerator(knight.getxPos(), knight.getyPos());
        }*/

        //int knightNewPosX = knight.getxPos() + rand.nextInt(2);
        //int knightNewPosY = knight.getyPos() + rand.nextInt(2);
        //knight.getComponent().setxCenter(generatedPos.x);
        //knight.getComponent().setyCenter(generatedPos.y);

        knight.setxPos(generatedPos.x);
        knight.setyPos(generatedPos.y);

        //int r = rand.nextInt(3);
        //System.out.print(r+" ");
        //Display.getInstance().updateComponent(knight);
    }
    public int whichRegion(int xPos, int yPos)
    {
        Random rand = new Random();
        int direction = rand.nextInt(3);
        int region = - 1;
        if(xPos < 575 && yPos < 400)
        {
            region = 0;
            /*if (direction == 0)
            {
                xPos = xPos + 1;
            }
            else if (direction == 1)
            {
                yPos = yPos + 1;
            } 
            if (direction == 2)
            {
                xPos = xPos + 1;
                yPos = yPos + 1;
            }*/
        }
        else if(xPos < 575 && yPos > 400)
        {
            region = 1;
            /*if (direction == 0)
            {
                xPos = xPos + 1;
            }
            else if (direction == 1)
            {
                yPos = yPos - 1;
            } 
            if (direction == 2)
            {
                xPos = xPos + 1;
                yPos = yPos - 1;
            }*/
        }
        else if(xPos > 575 && yPos < 400)
        {
            region = 2;
            /*if (direction == 0)
            {
                xPos = xPos - 1;
            }
            else if (direction == 1)
            {
                yPos = yPos + 1;
            } 
            if (direction == 2)
            {
                xPos = xPos - 1;
                yPos = yPos + 1;
            }*/ 
        }
        else if(xPos > 575 && yPos > 400)
        {
            region = 3;
            /*if (direction == 0)
            {
                xPos = xPos - 1;
            }
            else if (direction == 1)
            {
                yPos = yPos - 1;
            } 
            if (direction == 2)
            {
                xPos = xPos - 1;
                yPos = yPos - 1;
            }*/
        }
        /*else
        {
            xPos = randomNumberGenerator(xPos, yPos).x;
            yPos = randomNumberGenerator(xPos, yPos).y;
        }*/
        //Pair pairPos = new Pair(xPos, yPos);
        return region;
    }
    public Pair moveCenter(int xPos, int yPos)
    {
        if(575-xPos > 0)
        {
            xPos = xPos + 2;
        }
        else if(575-xPos < 0)
        {
            xPos = xPos - 2;
        }
        
        if(yPos - 400 > 0)
        {
            yPos = yPos - 2;
        }
        else if(yPos - 400 < 0)
        {
            yPos = yPos + 2;
        }
        Pair pairPos = new Pair(xPos, yPos);
        return pairPos;   
    }
    
    public Pair randomNumberGenerator(int xPos, int yPos, int speed) {
        Random rand = new Random();
        
        boolean check = true;
        
        int region = whichRegion(xPos, yPos);

        while (true) {
            int num = rand.nextInt(8);
       
            // move right
            if (num == 0) {
                if (xPos < 1050) {
                    xPos = xPos + (speed/25);
                    check = true;
                    break;

                }
            } // move up right
            else if (num == 1) {
                if (xPos < 1050 && yPos > 15) {
                    xPos = xPos + (speed/25);
                    yPos = yPos - (speed/25);
                    check = true;
                    break;
                }
            } // move up 
            else if (num == 2) {
                if (yPos > 15) {
                    yPos = yPos - (speed/25);
                    check = true;
                    break;
                }
            } // move up left  
            else if (num == 3) {
                if (xPos > 30 && yPos > 15) {
                    xPos = xPos - (speed/25);
                    yPos = yPos - (speed/25);
                    check = true;
                    break;
                }
            } // move left  
            else if (num == 4) {
                if (xPos > 30) {
                    xPos = xPos - (speed/25);
                    check = true;
                    break;
                }
            } // move down left 
            else if (num == 5) {
                if (xPos > 30 && yPos < 700) {
                    xPos = xPos - (speed/25);
                    yPos = yPos + (speed/25);
                    check = true;
                    break;
                }
            } //move down 
            else if (num == 6) {
                if (yPos < 700) {
                    yPos = yPos + (speed/25);
                    check = true;
                    break;
                }
            } // move down right 
            else if (num == 7) {
                if (xPos < 1050 && yPos < 700) {
                    xPos = xPos + (speed/25);
                    yPos = yPos + (speed/25);
                    check = true;
                    break;
                }
            }
        }
        /*
         if (x == 0) {
         // not move
         } else if (x == 1) {
         if (xPos > 1075) {

         } else {
         x = xPos + 1;
         }
         } else if (x == 2) {
         if (xPos < 380) {

         } else {
         xPos = xPos - 1;
         }
         }

         if (y == 0) {
         // not move
         } else if (y == 1) {
         if (yPos > 550) {

         } else {
         yPos = yPos + 1;
         }
         } else if (y == 2) {
         if (yPos < 12) {

         } else {
         yPos = yPos - 1;
         }
         }*/
        Pair pairPos = new Pair(xPos, yPos);
        return pairPos;
    }
}
