
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : Grade3Decorator.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//
public class Grade3Decorator extends KnightDecorator {

    public Grade3Decorator(Knight knightToBeDecorated) {
        super(knightToBeDecorated);
    }

    @Override
    public void draw(Graphics g) {
        super.draw(g);
        if (this.getType() == 2) {

            Graphics2D g2d = (Graphics2D) g.create();
            int xtopleft = this.getxPos();
            int ytopleft = this.getyPos();

            g2d.setColor(Color.CYAN);
            g2d.drawOval(xtopleft, ytopleft, 3, 3);
            g2d.fillOval(xtopleft, ytopleft, 3, 3);
            

        } else if (this.getType() == 0) {

            Graphics2D g2d = (Graphics2D) g.create();
            int xtopleft = this.getxPos();
            int ytopleft = this.getyPos();

            g2d.setColor(Color.CYAN);
            g2d.drawOval(xtopleft, ytopleft, 3, 3);
            g2d.fillOval(xtopleft, ytopleft, 3, 3);
            

        } else if (this.getType() == 1) {

            Graphics2D g2d = (Graphics2D) g.create();
            int xtopleft = this.getxPos();
            int ytopleft = this.getyPos();

            g2d.setColor(Color.CYAN);
            g2d.drawOval(xtopleft, ytopleft + 20, 3, 3);
            g2d.fillOval(xtopleft, ytopleft + 20, 3, 3);
            

        }
    }
}
