//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : Knight.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//

import java.util.*;
import java.awt.Graphics;

public abstract class Knight {

    private int hitPoint;
    private int score;
    private int speed;
    private int health;
    private int xPos;
    private int yPos;
    private Strategy strategy;
    private int team;
    private int type;
    private Knight target;
    private int id;
    private int timer;
    private int flag;
    private int stratTimer;
    private int specialFlag;
    private int dead;
    
    public Knight()
    {}
    
    public Knight(int id, int xPos, int yPos, int hitPoint, int score, int speed, int health,
            Strategy strategy, int team, int type, Knight target) {
        this.specialFlag = 0;
        this.stratTimer = 0;
        this.flag = 0;
        this.timer = 0;
        this.xPos = xPos;
        this.yPos = yPos;
        this.hitPoint = hitPoint;
        this.score = score;
        this.speed = speed;
        this.health = health;
        this.strategy = strategy;
        this.team = team;
        this.type = type;
        this.target = target;
        this.id = id;
        this.dead = 0;
    }

    public boolean rangedAttack(){
        return false;
    }

    public boolean meleeAttack(){
        return false;
    }

    public abstract void draw(Graphics g);
    
    public boolean healMe()
    {
        return false;
    }

    /*public void applyDmg(Object int)
     {
    
     }*/
    public void act() {
        this.getStrategy().act(this);
    }

    /**
     * @return the hitPoint
     */
    public int getHitPoint() {
        return hitPoint;
    }

    /**
     * @param hitPoint the hitPoint to set
     */
    public void setHitPoint(int hitPoint) {
        this.hitPoint = hitPoint;
    }

    /**
     * @return the score
     */
    public int getScore() {
        return score;
    }

    /**
     * @param score the score to set
     */
    public void setScore(int score) {
        this.score = score;
    }

    /**
     * @return the speed
     */
    public int getSpeed() {
        return speed;
    }

    /**
     * @param speed the speed to set
     */
    public void setSpeed(int speed) {
        this.speed = speed;
    }

    /**
     * @return the health
     */
    public int getHealth() {
        return health;
    }

    /**
     * @param health the health to set
     */
    public void setHealth(int health) {
        this.health = health;
    }

    /**
     * @return the xPos
     */
    public int getxPos() {
        return xPos;
    }

    /**
     * @param xPos the xPos to set
     */
    public void setxPos(int xPos) {
        this.xPos = xPos;
    }

    /**
     * @return the yPos
     */
    public int getyPos() {
        return yPos;
    }

    /**
     * @param yPos the yPos to set
     */
    public void setyPos(int yPos) {
        this.yPos = yPos;
    }

    /**
     * @return the strategy
     */
    public Strategy getStrategy() {
        return strategy;
    }

    /**
     * @param strategy the strategy to set
     */
    public void setStrategy(Strategy strategy) {
        this.strategy = strategy;
    }

    /**
     * @return the team
     */
    public int getTeam() {
        return team;
    }

    /**
     * @param team the team to set
     */
    public void setTeam(int team) {
        this.team = team;
    }

    /**
     * @return the type
     */
    public int getType() {
        return type;
    }

    /**
     * @param type the type to set
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * @return the target
     */
    public Knight getTarget() {
        return target;
    }

    /**
     * @param target the target to set
     */
    public void setTarget(Knight target) {
        this.target = target;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the timer
     */
    public int getTimer() {
        return timer;
    }

    /**
     * @param timer the timer to set
     */
    public void setTimer(int timer) {
        this.timer = timer;
    }

    /**
     * @return the flag
     */
    public int getFlag() {
        return flag;
    }

    /**
     * @param flag the flag to set
     */
    public void setFlag(int flag) {
        this.flag = flag;
    }

    /**
     * @return the stratTimer
     */
    public int getStratTimer() {
        return stratTimer;
    }

    /**
     * @param stratTimer the stratTimer to set
     */
    public void setStratTimer(int stratTimer) {
        this.stratTimer = stratTimer;
    }

    /**
     * @return the specialFlag
     */
    public int getSpecialFlag() {
        return specialFlag;
    }

    /**
     * @param specialFlag the specialFlag to set
     */
    public void setSpecialFlag(int specialFlag) {
        this.specialFlag = specialFlag;
    }

    /**
     * @return the dead
     */
    public int getDead() {
        return dead;
    }

    /**
     * @param dead the dead to set
     */
    public void setDead(int dead) {
        this.dead = dead;
    }
}
