
import java.awt.Graphics;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Offline
//  @ File Name : KnightDecorator.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//
public abstract class KnightDecorator extends Knight {

    protected Knight knightToDecorated;

    public KnightDecorator(Knight knightToBeDecorated) {
        this.knightToDecorated = knightToBeDecorated;
    }

    @Override
    public void draw(Graphics g) {
        this.knightToDecorated.draw(g);
    }

    @Override
    public void setDead(int dead) {
        knightToDecorated.setDead(dead); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getDead() {
        return knightToDecorated.getDead(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setSpecialFlag(int specialFlag) {
        knightToDecorated.setSpecialFlag(specialFlag); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getSpecialFlag() {
        return knightToDecorated.getSpecialFlag(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setStratTimer(int stratTimer) {
        knightToDecorated.setStratTimer(stratTimer); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getStratTimer() {
        return knightToDecorated.getStratTimer(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setFlag(int flag) {
        knightToDecorated.setFlag(flag); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getFlag() {
        return knightToDecorated.getFlag(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setTimer(int timer) {
        knightToDecorated.setTimer(timer); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getTimer() {
        return knightToDecorated.getTimer(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setId(int id) {
        knightToDecorated.setId(id); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getId() {
        return knightToDecorated.getId(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setTarget(Knight target) {
        knightToDecorated.setTarget(target); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Knight getTarget() {
        return knightToDecorated.getTarget(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setType(int type) {
        knightToDecorated.setType(type); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getType() {
        return knightToDecorated.getType(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setTeam(int team) {
        knightToDecorated.setTeam(team); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getTeam() {
        return knightToDecorated.getTeam(); //To change body of generated methods, choose Tools | Templates.
    }

   
    @Override
    public void setStrategy(Strategy strategy) {
        knightToDecorated.setStrategy(strategy); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Strategy getStrategy() {
        return knightToDecorated.getStrategy(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setyPos(int yPos) {
        knightToDecorated.setyPos(yPos); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getyPos() {
        return knightToDecorated.getyPos(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setxPos(int xPos) {
        knightToDecorated.setxPos(xPos); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getxPos() {
        return knightToDecorated.getxPos(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setHealth(int health) {
        knightToDecorated.setHealth(health); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getHealth() {
        return knightToDecorated.getHealth(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setSpeed(int speed) {
        knightToDecorated.setSpeed(speed); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getSpeed() {
        return knightToDecorated.getSpeed(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setScore(int score) {
        knightToDecorated.setScore(score); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getScore() {
        return knightToDecorated.getScore(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setHitPoint(int hitPoint) {
        knightToDecorated.setHitPoint(hitPoint); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getHitPoint() {
        return knightToDecorated.getHitPoint(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void act() {
        knightToDecorated.act(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean healMe() {
        return knightToDecorated.healMe();
    }

    @Override
    public boolean meleeAttack() {
        return knightToDecorated.meleeAttack(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean rangedAttack() {
        return knightToDecorated.rangedAttack(); //To change body of generated methods, choose Tools | Templates.
    }

}
