//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : MageFactory.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//

public class MageFactory extends SoldierFactory {

    @Override
    public Knight produce(int team, int id) {
        // TODO Auto-generated method stub
        if (team == 0) { //KARUS
            Strategy strategy = new MoveRandomly();
            Mage mage = new Mage(id,200, 550, 100, 0, 75, 400, strategy, 0, 1,null);

            // TODO
            Simulation.getInstance().getKarusList().add(mage);
        } else {
            Strategy strategy = new MoveRandomly();
            Mage mage = new Mage(id,900, 200, 100, 0, 75, 400, strategy, 1, 1,null);

            // TODO
            Simulation.getInstance().getElmoradList().add(mage);
        }
        return null;
    }
}
