
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : Grade3Decorator.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//
public class NoobDecorator extends KnightDecorator {

    public NoobDecorator(Knight knightToBeDecorated) {
        super(knightToBeDecorated);
    }

    @Override
    public void draw(Graphics g) {
        super.draw(g);
    }
}
