//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : PriestFactory.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//

public class PriestFactory extends SoldierFactory {

    @Override
    public Knight produce(int team, int id) {
        // TODO Auto-generated method stub
        if (team == 0) { //KARUS
            Strategy strategy = new MoveRandomly();
            
            Priest priest = new Priest(id,200, 550, 150, 0, 50, 350, strategy, 0,2,null);

            Simulation.getInstance().getKarusList().add(priest);
        } else {
            Strategy strategy = new MoveRandomly();
            
            Priest priest = new Priest(id,900, 200, 150,0, 50, 350, strategy, 1,2,null);

            Simulation.getInstance().getElmoradList().add(priest);
        }

        return null;
    }

}
