//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : SoldierFactory.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//

public abstract class SoldierFactory {

    public Team team;

    public abstract Knight produce(int team,int id);
}
