//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Knight Ofline
//  @ File Name : Strategy.java
//  @ Date : @31.03.2015
//  @ Author : @Burak Araz
//
//




public abstract class Strategy
{

    public abstract void act(Knight knight);
}
